name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🎉 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🚑 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⬆️ Update'
    label: 'update'
  - title: '➖ Removed'
    label: 'remove'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # 🔨 Changes

  $CHANGES
