name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ github.ref }}"' custom_components/anniversaries/const.py
          sed -i '  "version": /c\  "version": "${{ github.ref }}",' custom_components/anniversaries/manifest.json
          sed -i 's|refs/heads/||' custom_components/anniversaries/const.py
          sed -i 's|refs/tags/||' custom_components/anniversaries/const.py

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP Anniversaries Dir
        run: |
          cd /home/runner/work/Anniversaries/Anniversaries/custom_components/anniversaries
          zip anniversaries.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Anniversaries/Anniversaries/custom_components/anniversaries/anniversaries.zip
          asset_name: anniversaries.zip
          tag: ${{ github.ref }}
          overwrite: true
